### ISSUE TITLE
cored crashes on startup if unelevated

### ISSUE THREAD

**Issue by miyu** [the-dargon-project/the-dargon-project#8]
Full Stack Dump:

```
System.Management.ManagementException was unhandled
  HResult=-2146233087
  Message=Access denied 
  Source=System.Management
  StackTrace:
       at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
       at System.Management.ManagementEventWatcher.Start()
       at Dargon.Processes.Watching.WmiProcessDiscoveryMethod.Start() in c:\my-repositories\the-dargon-project\libdargon.process-impl\Watching\WmiProcessDiscoveryMethod.cs:line 55
       at Dargon.Processes.Watching.ProcessWatcher.Start() in c:\my-repositories\the-dargon-project\libdargon.process-impl\Watching\ProcessWatcher.cs:line 60
       at Dargon.Processes.Watching.ProcessWatcherServiceImpl.Initialize() in c:\my-repositories\the-dargon-project\libdargon.process-impl\Watching\ProcessWatcherServiceImpl.cs:line 30
       at Dargon.Daemon.CoreDaemonApplicationEgg.<>c.<CreateDaemonCore>b__7_1(ProcessWatcherServiceImpl s) in c:\my-repositories\the-dargon-project\daemon-impl\CoreDaemonEgg.cs:line 174
       at ItzWarty.Extend.With[T](T self, Action`1 func)
       at Dargon.Daemon.CoreDaemonApplicationEgg.CreateDaemonCore(IEggParameters parameters, List`1& keepalive) in c:\my-repositories\the-dargon-project\daemon-impl\CoreDaemonEgg.cs:line 174
       at Dargon.Daemon.CoreDaemonApplicationEgg.Start(IEggParameters parameters) in c:\my-repositories\the-dargon-project\daemon-impl\CoreDaemonEgg.cs:line 55
       at nest_host.EggHost.Run(BootstrapDto bootstrapArguments) in c:\my-repositories\Dargon.Nest\nest-host\EggHost.cs:line 32
       at nest_host.Program.Main(String[] args) in c:\my-repositories\Dargon.Nest\nest-host\Program.cs:line 64
  InnerException: 
```

**Comment by miyu** [comment]
Ideally, we'd notify the users about this through a dialog box or request elevation.

**Comment by miyu** [comment]
This might be a bit messy as we launch as a nest hatchling (we can't just relaunch with a runas). It might make more sense to require nestd to launch elevated or to have a nest exec flag that indicates a need for elevation (followed by a UAC popup).

**Comment by miyu** [comment]
nestd and nest-spawner now request admin privileges which solves this issue: https://github.com/the-dargon-project/Dargon.Nest/commit/5d0128641d69d780e8038ac779944a15269dbb03
